openai_token_file: "/home/galimzyanov/tokens/chat-gpt4.txt"
seaborn_out_path: "/mnt/data2/galimzyanov/plots_benchmark/seaborn"
matplotlib_dataset_path: "/mnt/data2/galimzyanov/plots_benchmark/matplotlib/dataset"
matplotlib_source_path: "/mnt/data2/galimzyanov/plots_benchmark/matplotlib/gallery_jupyter_source"
validated_notebooks: "/mnt/data2/galimzyanov/plots_benchmark/matplotlib/validated_notebooks"
dataset_valid_step_1: "/mnt/data2/galimzyanov/plots_benchmark/matplotlib/dataset_valid_step_1"
dataset_valid_step_1_notebooks: "/mnt/data2/galimzyanov/plots_benchmark/matplotlib/dataset_valid_step_1_notebooks"
dataset_final: "/mnt/data2/galimzyanov/plots_benchmark/matplotlib/dataset_final"
out_folder: "/mnt/data2/galimzyanov/plots_benchmark/matplotlib/out_results"